categories:
  - title: "🚀 Features"
    labels: [feature]
  - title: "🐛 Bug Fixes"
    labels: [bug]

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
files: |
	manifest.json
	main.js
	style.css

template: |
  # 发布日志

  ## 变更
  $CHANGES

  ## 贡献者
  $CONTRIBUTORS