name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}