name: Release Drafter

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v6
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
